// <auto-generated />
using System;
using MS.SS.Core.Infrastructure.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MS.SS.Core.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928154941_AddReceptionSchema")]
    partial class AddReceptionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MS.SS.Core.Modules.Identity.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("MS.SS.Core.Modules.Reception.Domain.Entities.Carton", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid>("PalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("pallet_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_cartons");

                    b.HasIndex("PalletId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_cartons_pallet_code");

                    b.ToTable("cartons", "reception");
                });

            modelBuilder.Entity("MS.SS.Core.Modules.Reception.Domain.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.HasKey("Id")
                        .HasName("pk_deliveries");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_deliveries_order_number");

                    b.ToTable("deliveries", "reception");
                });

            modelBuilder.Entity("MS.SS.Core.Modules.Reception.Domain.Entities.Pallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("pk_pallets");

                    b.HasIndex("DeliveryId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_pallets_delivery_code");

                    b.ToTable("pallets", "reception");
                });

            modelBuilder.Entity("MS.SS.Core.Modules.Reception.Domain.Entities.ProductLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CartonId")
                        .HasColumnType("uuid")
                        .HasColumnName("carton_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("expected_quantity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("ReceivedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("received_quantity");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_product_lines");

                    b.HasIndex("CartonId", "Reference")
                        .IsUnique()
                        .HasDatabaseName("ux_product_lines_carton_reference");

                    b.ToTable("product_lines", "reception", t =>
                        {
                            t.HasCheckConstraint("ck_product_lines_expected_positive", "expected_quantity > 0");

                            t.HasCheckConstraint("ck_product_lines_received_bounds", "received_quantity >= 0 AND received_quantity <= expected_quantity");
                        });
                });

            modelBuilder.Entity("MS.SS.Core.Modules.Reception.Domain.Entities.Carton", b =>
                {
                    b.HasOne("MS.SS.Core.Modules.Reception.Domain.Entities.Pallet", null)
                        .WithMany("Cartons")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartons_pallet_pallet_id");
                });

            modelBuilder.Entity("MS.SS.Core.Modules.Reception.Domain.Entities.Pallet", b =>
                {
                    b.HasOne("MS.SS.Core.Modules.Reception.Domain.Entities.Delivery", null)
                        .WithMany("Pallets")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pallets_deliveries_delivery_id");
                });

            modelBuilder.Entity("MS.SS.Core.Modules.Reception.Domain.Entities.ProductLine", b =>
                {
                    b.HasOne("MS.SS.Core.Modules.Reception.Domain.Entities.Carton", null)
                        .WithMany("Products")
                        .HasForeignKey("CartonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_lines_cartons_carton_id");
                });

            modelBuilder.Entity("MS.SS.Core.Modules.Reception.Domain.Entities.Carton", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MS.SS.Core.Modules.Reception.Domain.Entities.Delivery", b =>
                {
                    b.Navigation("Pallets");
                });

            modelBuilder.Entity("MS.SS.Core.Modules.Reception.Domain.Entities.Pallet", b =>
                {
                    b.Navigation("Cartons");
                });
#pragma warning restore 612, 618
        }
    }
}
