<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="WolverineFx" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MS.SS.Core.Infrastructure\MS.SS.Core.Infrastructure.csproj" />
    <ProjectReference Include="..\MS.SS.Core.Modules.Identity\MS.SS.Core.Modules.Identity.csproj" />
    <ProjectReference Include="..\MS.SS.Core.Modules.Reception\MS.SS.Core.Modules.Reception.csproj" />
    <ProjectReference Include="..\MS.SS.Core.Security\MS.SS.Core.Security.csproj" />
    <ProjectReference Include="..\MS.SS.Core.SharedKernel\MS.SS.Core.SharedKernel.csproj" />
  </ItemGroup>

</Project>
